### ISSUE TITLE
[fix] Notes field in task details should be a text area

### ISSUE THREAD

**Issue by Nicryc** [done-devs/done#102]
**Describe the feature you'd like**
The notes field in the task details view should be a text area (a multiline text input). A note is often a long text so it is not very practical to be forced to scroll horizontally to see the whole note.

**Additional context**

![Screenshot from 2023-06-09 20-58-44](https://github.com/done-devs/done/assets/15157120/2c901b2c-d983-4f93-9548-68b0d1cadead)

**Comment by edfloreshz** [comment]
Yep, I'll change it in the next release, thanks 😄
