### ISSUE TITLE
table lists already exists

### ISSUE THREAD

**Issue by sonnyp** [done-devs/done#105]
**Describe the bug**

I installed the app a while ago and wanted to try it today.
Starting the app fails.

Same issue as https://github.com/done-devs/done/issues/100 but I don't think it should have been closed.

**To Reproduce**

I don't know.

**Expected behavior**

The app should never fail to start.

**Additional context**

```
sonny@porygon ~ [1]> flatpak info dev.edfloreshz.Done

Done - To-do lists reimagined

          ID: dev.edfloreshz.Done
         Ref: app/dev.edfloreshz.Done/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 0.1.7
     License: MPL-2.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 5,4 MB
     Runtime: org.gnome.Platform/x86_64/43
         Sdk: org.gnome.Sdk/x86_64/43

      Commit: 33daf6f6299cb32aaf62f4e071ad0d5e9cbd5c4060857076f39d1e4344b02a42
      Parent: 7bbb588a1f4912d23e8bb3843de3cd494bea6654b43ae2b1a04de924179ecf56
     Subject: v0.1.7 (e536dbbf)
        Date: 2023-05-22 02:04:38 +0000
```

Looks like a migration issue

```
sonny@porygon ~ [1]> flatpak run dev.edfloreshz.Done
Error: Failed to run 2023-05-16-035137_create_lists with: table lists already exists
```

**Comment by edfloreshz** [comment]
Thanks for letting me know, I'm aware of this and working on it. The next release will include this fix.

**Comment by edfloreshz** [comment]
[4eb6643](https://github.com/done-devs/done/commit/4eb66434475fe284af1cc2318ffdc43a47360605) fixes this issue.
