### ISSUE TITLE
Extremely verbose

### ISSUE THREAD

**Issue by hfiguiere** [done-devs/done#110]
**Describe the bug**
Done do spam the console with extremely verbose logs. At least the flatpak does.

**To Reproduce**
1. Launch Done in a termninal
2. Type something to create a new task
3. Each key stroke generate a log line

**Expected behavior**
"INFO" log entries are never shown unless explicitely requested

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version flatpak

**Additional context**
If launched form the gnome-sheel, `journalctl -r` is flooded instead.

**Comment by edfloreshz** [comment]
Fixed with [8cec44a](https://github.com/done-devs/done/commit/8cec44a5db0fcfeca287698536d4dc2c772b1122#diff-4b3097a5102b676e768d939061c65fad621d6f9b48d8396f19841219783570f7)
