### ISSUE TITLE
Adwaita-WARNING **: AdwNavigationPage is missing a title. 

### ISSUE THREAD

**Issue by wada3n** [done-devs/done#114]
**Describe the bug**
When i try to run the app, this message appears and it does not start.

> (done:2): Adwaita-WARNING **: 19:23:14.721: AdwNavigationPage 0x55ee8c961d20 is missing a title. To hide a header bartitle, consider using AdwHeaderBar:show-title instead.

**Desktop (please complete the following information):**
 - OS: Fedora 39
 - Flatpak V: 1.15.4

**Comment by edfloreshz** [comment]
Closed by c3177426ef95fefe04b4f4d2be7d5dd44752b971
