### ISSUE TITLE
[feat] Expand sub-tasks

### ISSUE THREAD

**Issue by fastrizwaan** [done-devs/done#116]
Sub tasks are hidden unless we click (i) button that too at the bottom after all the options, as if they are insignificant, please allow by default to expand sub tasks, so that they are visible.

Task
1. Breakfast
3. Lunch
4. Dinner

E.g. Here's  list of Breakfast items

![image](https://github.com/done-devs/done/assets/1161682/33c61808-4efb-46a9-a414-5cf49ae4749c)

The items in 

1. Protein

- [ ] Eggs
- [] Cheese

3. Carbohydrates
4. Liquids

![image](https://github.com/done-devs/done/assets/1161682/6bccaf45-4ea3-4beb-a569-a336e8c0652f)

Example Errands show the task and sub-tasks with a drop-down list
![image](https://github.com/done-devs/done/assets/1161682/58d180c7-a2bb-4769-a35f-a99befa5fb8f)

**Comment by edfloreshz** [comment]
I recently made it possible to expand tasks and see their details, I'm thinking that we could have two different tabs when you expand a task:

- One for the details of the task.
- Another for the sub tasks.

We could enable expansion for sub-tasks there.

**Comment by edfloreshz** [comment]
After careful consideration and experimentation I have decided not to implement this.

![image](https://github.com/done-devs/done/assets/22224438/a3b3b74e-2e51-494a-9fce-a7c048d909a2)

As you can see with Errands, at some point you run out of space and it just doesn't look good.

Thanks for suggesting it!
