### ISSUE TITLE
An easy way to back up my local tasks and import back into Done on a fresh Linux install 

### ISSUE THREAD

**Issue by tomhoughton** [done-devs/done#33]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by edfloreshz** [comment]
Thanks, I'll look into this. 

In the meantime, you can copy the .db file inside the `~/.local/share/done/` from your previous installation to your new one.

**Comment by edfloreshz** [comment]
We have decided to stop developing Done in favor of [Rememberance](https://github.com/dgsasha/remembrance), please consider switching to it.
