### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by CodeCubeNeo** [done-devs/done#6]
Since this is very new maybe i would ask for cross platform support?

**Comment by edfloreshz** [comment]
Windows support is in the plans, I haven't had a chance to test it there but it's theoretically possible.

An installer will be released in the near future.

**Comment by CodeCubeNeo** [comment]
Awesome!

**Comment by CodeCubeNeo** [comment]
Another recomendation i have is to save the tasks in the tasks.org format (json), since the tasks.org mobile app is looking for cross platform compatibility and this could be it (it has a large userbase, so more people could help you with this project? idk just an idea).

**Comment by edfloreshz** [comment]
Sounds interesting, I'll look into that.

**Comment by CodeCubeNeo** [comment]
Great. Then it would be an ultimate cross platform solution. Really looking forward

**Comment by edfloreshz** [comment]
Great! Thanks you.

Would you please open an issue for this and link all the related info you can? I'll work on the issue templates later today for the repo.

**Comment by edfloreshz** [comment]
I just implemented the plugin system, we could build a plugin for Tasks.org to support this.

**Comment by edfloreshz** [comment]
We have decided to stop developing Done in favor of [Rememberance](https://github.com/dgsasha/remembrance), please consider switching to it.

**Comment by edfloreshz** [comment]
This app will continue to be developed, reopening! 🎉
