### ISSUE TITLE
Save tasks in the tasks.org way

### ISSUE THREAD

**Issue by CodeCubeNeo** [done-devs/done#7]
Hello! I think it would be great to save the tasks in the same json format as tasks.org does. Here is the link to their github repository: https://github.com/tasks/tasks.

**Comment by shuvashish76** [comment]
reference issue : https://github.com/tasks/tasks/issues/1256

**Comment by edfloreshz** [comment]
I just implemented the plugin system, we could build a plugin for Tasks.org to support this.

**Comment by CodeCubeNeo** [comment]
Any progress on this?

**Comment by edfloreshz** [comment]
Not yet, but it would be a nice addition to the [local plugin](https://github.com/done-devs/local-plugin), which currently uses SQLite to store the tasks.

**Comment by CodeCubeNeo** [comment]
By "Not yet", did you mean there is a plan to create it? Also why not just replace the default way of storing todos in the tasks.org way instead of a yet again new detabase format for todos. (you can implement just the basics for now (tasks.org stores it in a json file))?

**Comment by edfloreshz** [comment]
@Kedap is making some progress in this area, we might end up implementing a plug-in for Tasks.org and making it available for Done.

**Comment by edfloreshz** [comment]
We have decided to stop developing Done in favor of [Rememberance](https://github.com/dgsasha/remembrance), please consider switching to it.
