### ISSUE TITLE
Add EteSync Support

### ISSUE THREAD

**Issue by krvkz** [done-devs/done#87]
**Describe the feature you'd like**
Add EteSync to the list of supported syncing services.

https://www.etesync.com/

**Additional context**
EteSync is an open-source "secure, end-to-end encrypted, and privacy respecting sync for your contacts, calendars, tasks and notes." There aren't any Linux desktop tasks apps that support EteSync apart from Evolution that I can find, and I think it's obvious why Evolution might not be everyone's first choice. EteSync's entire ethos makes a lot of sense for Linux users, but I think it's too new for any projects to have adopted it so far. It would be awesome to see Done implement this.

**Comment by edfloreshz** [comment]
I'll take a look into it 🥳

**Comment by edfloreshz** [comment]
We have decided to stop developing Done in favor of [Rememberance](https://github.com/dgsasha/remembrance), please consider switching to it.
