### ISSUE TITLE
Weird positioning 

### ISSUE THREAD

**Issue by hugofintecture** [done-devs/done#88]
Hello! 

Just a small issue with some elements :) Happens with French translation.

![image](https://user-images.githubusercontent.com/89129201/233029673-67aa107a-63cd-4739-949a-9bd407ab0164.png)

**Comment by edfloreshz** [comment]
Hey, thanks for the bug report, I will take a look at it.

**Comment by edfloreshz** [comment]
We have decided to stop developing Done in favor of [Rememberance](https://github.com/dgsasha/remembrance), please consider switching to it.
